
modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="geopolitics"
version="1.0.0"
displayName="Geopolitics"
description='''
Faction-style geopolitical system for Forge 1.20.1.
'''
