
name: Build Forge Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Mod
        run: ./gradlew build

      - name: Upload built mod
        uses: actions/upload-artifact@v3
        with:
          name: GeopoliticsMod
          path: build/libs/*.jar
